name: Build Document
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Save result
        uses: actions/upload-artifact@v3
        with:
          name: document
          path: main.pdf
